using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace AtomUIGallery.Generator;

/// <summary>
/// 源生成器：為 ShowCaseItem 生成 SourceCode 內容
/// </summary>
[Generator]
public class ShowCaseSourceCodeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 監聽所有 .axaml 文件
        var axamlFiles = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(".axaml", StringComparison.OrdinalIgnoreCase) &&
                           file.Path.Contains("ShowCases"));

        // 組合所有 axaml 文件
        var axamlContents = axamlFiles.Select((file, cancellationToken) =>
        {
            var text = file.GetText(cancellationToken)?.ToString() ?? string.Empty;
            return (Path: file.Path, Content: text);
        }).Collect();

        // 生成代碼
        context.RegisterSourceOutput(axamlContents, (spc, files) =>
        {
            GenerateSourceCode(spc, files);
        });
    }

    private void GenerateSourceCode(SourceProductionContext context,
        ImmutableArray<(string Path, string Content)> files)
    {
        var parser = new ShowCaseItemAxamlParser();
        var allShowCases = new Dictionary<string, List<ShowCaseItemInfo>>();

        foreach (var (path, content) in files)
        {
            if (string.IsNullOrWhiteSpace(content)) continue;

            var showCaseItems = parser.Parse(content, path);
            if (showCaseItems.Count > 0)
            {
                // 從路徑中提取類名
                var className = GetClassNameFromPath(path, content);
                if (!string.IsNullOrEmpty(className))
                {
                    allShowCases[className] = showCaseItems;
                }
            }
        }

        if (allShowCases.Count == 0) return;

        // 生成主類
        var sourceBuilder = new StringBuilder();
        sourceBuilder.AppendLine("// <auto-generated />");
        sourceBuilder.AppendLine("#nullable enable");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("using System.Collections.Generic;");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("namespace AtomUIGallery.ShowCases;");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("/// <summary>");
        sourceBuilder.AppendLine("/// 自動生成的 ShowCase 源代碼提供者");
        sourceBuilder.AppendLine("/// </summary>");
        sourceBuilder.AppendLine("public static class ShowCaseSourceCodeProvider");
        sourceBuilder.AppendLine("{");

        // 生成靜態字典存儲所有 ShowCase 的源代碼
        sourceBuilder.AppendLine("    private static readonly Dictionary<string, Dictionary<int, string>> _sourceCodes = new()");
        sourceBuilder.AppendLine("    {");

        foreach (var kvp in allShowCases)
        {
            var className = kvp.Key;
            var items = kvp.Value;
            if (items is null) {
                continue;
            }

            sourceBuilder.AppendLine($"        [\"{className}\"] = new Dictionary<int, string>");
            sourceBuilder.AppendLine("        {");

            foreach (var item in items)
            {
                var escapedContent = EscapeForVerbatimString(item.ContentXaml);
                sourceBuilder.AppendLine($"            [{item.Index}] = @\"{escapedContent}\",");
            }

            sourceBuilder.AppendLine("        },");
        }

        sourceBuilder.AppendLine("    };");
        sourceBuilder.AppendLine();

        // 生成獲取源代碼的方法
        sourceBuilder.AppendLine("    /// <summary>");
        sourceBuilder.AppendLine("    /// 獲取指定 ShowCase 頁面中指定索引的 ShowCaseItem 的源代碼");
        sourceBuilder.AppendLine("    /// </summary>");
        sourceBuilder.AppendLine("    /// <param name=\"className\">ShowCase 類名</param>");
        sourceBuilder.AppendLine("    /// <param name=\"index\">ShowCaseItem 的索引（從 0 開始）</param>");
        sourceBuilder.AppendLine("    /// <returns>AXAML 源代碼字符串，如果未找到則返回 null</returns>");
        sourceBuilder.AppendLine("    public static string? GetSourceCode(string className, int index)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine("        if (_sourceCodes.TryGetValue(className, out var items))");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            if (items.TryGetValue(index, out var sourceCode))");
        sourceBuilder.AppendLine("            {");
        sourceBuilder.AppendLine("                return sourceCode;");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine("        return null;");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        // 生成通過 Type 獲取的重載方法
        sourceBuilder.AppendLine("    /// <summary>");
        sourceBuilder.AppendLine("    /// 獲取指定 ShowCase 頁面中指定索引的 ShowCaseItem 的源代碼");
        sourceBuilder.AppendLine("    /// </summary>");
        sourceBuilder.AppendLine("    /// <param name=\"showCaseType\">ShowCase 頁面的類型</param>");
        sourceBuilder.AppendLine("    /// <param name=\"index\">ShowCaseItem 的索引（從 0 開始）</param>");
        sourceBuilder.AppendLine("    /// <returns>AXAML 源代碼字符串，如果未找到則返回 null</returns>");
        sourceBuilder.AppendLine("    public static string? GetSourceCode(System.Type showCaseType, int index)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine("        return GetSourceCode(showCaseType.Name, index);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        // 生成獲取所有源代碼的方法
        sourceBuilder.AppendLine("    /// <summary>");
        sourceBuilder.AppendLine("    /// 獲取指定 ShowCase 頁面的所有 ShowCaseItem 源代碼");
        sourceBuilder.AppendLine("    /// </summary>");
        sourceBuilder.AppendLine("    /// <param name=\"className\">ShowCase 類名</param>");
        sourceBuilder.AppendLine("    /// <returns>索引到源代碼的字典，如果未找到則返回 null</returns>");
        sourceBuilder.AppendLine("    public static Dictionary<int, string>? GetAllSourceCodes(string className)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine("        if (_sourceCodes.TryGetValue(className, out var items))");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            return new Dictionary<int, string>(items);");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine("        return null;");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine("    /// <summary>");
        sourceBuilder.AppendLine("    /// 獲取所有已註冊的 ShowCase 類名");
        sourceBuilder.AppendLine("    /// </summary>");
        sourceBuilder.AppendLine("    public static IEnumerable<string> GetAllShowCaseNames()");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine("        return _sourceCodes.Keys;");
        sourceBuilder.AppendLine("    }");

        sourceBuilder.AppendLine("}");

        context.AddSource("ShowCaseSourceCodeProvider.g.cs",
            SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
    }

    private string GetClassNameFromPath(string path, string content)
    {
        // 首先嘗試從 x:Class 屬性中獲取類名
        var classMatch = System.Text.RegularExpressions.Regex.Match(
            content, @"x:Class=""([^""]+)""");

        if (classMatch.Success)
        {
            var fullClassName = classMatch.Groups[1].Value;
            // 返回不帶命名空間的類名
            var lastDot = fullClassName.LastIndexOf('.');
            return lastDot >= 0 ? fullClassName.Substring(lastDot + 1) : fullClassName;
        }

        // 從文件路徑中獲取
        var fileName = Path.GetFileNameWithoutExtension(path);
        return fileName;
    }

    private string EscapeForVerbatimString(string input)
    {
        // 對於 verbatim string，只需要將 " 替換為 ""
        return input.Replace("\"", "\"\"");
    }
}
